Repository Sylius/PayPalPlugin, pull requests merged in 2020-12, with the labels that each got.

#160 Support Doctrine Migrations ^3.0
  .github/workflows/build.yml
  UPGRADE.md
  composer.json
  docs/installation.md
  psalm.xml
  src/DependencyInjection/SyliusPayPalExtension.php
  src/Migrations/Version20200907102535.php
Labels: Enhancement, Maintenance

#163 Check if migrations are generated in proper directory
  .github/workflows/build.yml
  etc/travis/Order.php
  etc/travis/resources.yaml
Labels: DX, Enhancement, Maintenance

#172 Adding new payment method fix
  features/trying_to_onboard_more_than_one_pay_pal_seller.feature
  spec/Listener/PayPalPaymentMethodListenerSpec.php
  src/Listener/PayPalPaymentMethodListener.php
  tests/Behat/Context/Admin/ManagingPaymentMethodsContext.php
Labels: Bug

#170 API Platform support
  spec/ApiPlatform/PayPalPaymentSpec.php
  src/ApiPlatform/PayPalPayment.php
  src/Resources/config/services.xml
Labels: Feature
