Repository Sylius/PayPalPlugin, pull requests merged in 2020-10, with the labels that each got.

#129 README improvements
  .travis.yml
  composer.json
  docs/installation.md
  docs/sandbox-vs-live.md
Labels: Enhancement

#132 webhook already registered exception
  src/Exception/PayPalWebhookAlreadyRegisteredException.php
  src/Onboarding/Processor/BasicOnboardingProcessor.php
  src/Registrar/SellerWebhookRegistrar.php
Labels: Enhancement

#134 Prepare to RC.2 release
  docs/installation.md
Labels: Maintenance

#135 Improve docs navigation
  docs/development.md
  docs/installation.md
  docs/onboarding.md
  docs/processing-payments.md
  docs/reports.md
  docs/sandbox-vs-live.md
Labels: Enhancement

#136 Allow only one seller to be onboarded
  features/trying_to_onboard_more_than_one_pay_pal_seller.feature
  spec/Listener/PayPalPaymentMethodListenerSpec.php
  src/Form/Extension/PaymentMethodTypeExtension.php
  src/Listener/PayPalPaymentMethodListener.php
  src/Provider/PayPalPaymentMethodProvider.php
  src/Resources/config/services.xml
  src/Resources/translations/flashes.en.yml
  src/Resources/views/Grid/enablePayPal.html.twig
  src/Twig/PayPalExtension.php
  tests/Application/config/services_test.yaml
  tests/Behat/Context/Admin/ManagingPaymentMethodsContext.php
  tests/Behat/Resources/services.xml
Labels: Bug, Enhancement, UX/UI

#144 Remove placeholder comment from admin_routing.yml
  src/Resources/config/admin_routing.yml
Labels: DX, Enhancement

#143 Always pass currency to PayPal
  src/Controller/PayPalButtonsController.php
  src/Resources/config/services/controller.xml
  src/Resources/views/payFromCartPage.html.twig
  src/Resources/views/payFromPaymentPage.html.twig
  src/Resources/views/payFromProductPage.html.twig
  src/Resources/views/payWithPaypal.html.twig
Labels: Bug

#149 Use Uuid Provider for PayPalCredentials
  spec/Api/CacheAuthorizeClientApiSpec.php
  src/Api/CacheAuthorizeClientApi.php
  src/Resources/config/services/api.xml
Labels: Enhancement

#148 Do not assign PayPal customer to order if the user is logged in
  src/Controller/ProcessPayPalOrderAction.php
Labels: Bug

#151 log payments error when onError triggers
  src/Controller/PayPalPaymentOnErrorAction.php
  src/Resources/config/services/controller.xml
  src/Resources/views/payFromCartPage.html.twig
  src/Resources/views/payFromPaymentPage.html.twig
  src/Resources/views/payFromProductPage.html.twig
  src/Resources/views/payWithPaypal.html.twig
Labels: Bug

#152 Process locales to match paypal requirements
  composer.json
  spec/Processor/LocaleProcessorSpec.php
  src/Controller/PayPalButtonsController.php
  src/Processor/LocaleProcessor.php
  src/Processor/LocaleProcessorInterface.php
  src/Resources/config/services.xml
  src/Resources/config/services/controller.xml
Labels: Bug
