Repository Sylius/PayPalPlugin, pull requests merged in 2020-11, with the labels that each got.

#153 Inform about empty billing address after PayPal checkout
  src/Api/CreateOrderApi.php
  src/Controller/ProcessPayPalOrderAction.php
  src/Resources/config/services.xml
  src/Resources/translations/messages.en.yml
  src/Resources/views/bundles/SyliusShopBundle/Common/Order/_addresses.html.twig
  src/Twig/OrderAddressExtension.php
Labels: Bug

#155 Prepare to 1.0 release in installation instruction
  docs/installation.md
Labels: Enhancement, Maintenance

#158 Check order has a shipping address in the PayPalAddressProcessor
  src/Processor/PayPalAddressProcessor.php
Labels: Bug

#161 [Migration] Adjust namespace to newest Sylius Standard
  etc/travis/sylius18/doctrine_migrations.yaml
  migrations/Version20200907102535.php
  tests/Application/config/packages/doctrine_migrations.yaml
  tests/Application/src/Migrations/Version20200604080033.php
Labels: Bug

#162 [Docs] Mention about https error
  docs/installation.md
  docs/onboarding.md
  docs/onboarding/http-error.png
Labels: Maintenance

#164 [Docs][Minor] Typo fix in onboarding
  docs/onboarding.md
Labels: Enhancement

#167 [Payum] Define resolve next route action only for paypal gateway
  src/Resources/config/services/payum.xml
Labels: Bug

#159 Require Sylius ^1.8
  .github/workflows/build.yml
  UPGRADE.md
  composer.json
  etc/travis/sylius18/bundles.php
  etc/travis/sylius18/doctrine_migrations.yaml
  etc/travis/sylius18/security.yaml
  tests/Application/config/bundles.php
  tests/Application/config/packages/doctrine_migrations.yaml
  tests/Application/config/packages/lexik_jwt_authentication.yaml
  tests/Application/config/packages/security.yaml
  tests/Application/config/routes/sylius_api.yaml
  tests/Application/src/Migrations/.gitkeep
  tests/Application/src/Migrations/Version20200604080033.php
Labels: Maintenance
