Repository Sylius/PayPalPlugin, pull requests merged in 2021-04, with the labels that each got.

#196 Temporarily lock on Sylius 1.8
  composer.json
Labels: Maintenance

#192 Fix service injection of CompletePayPalOrderFromPaymentPageAction
  src/Resources/config/services/controller.xml
Labels: Bug

#193 Add french translation
  src/Resources/translations/flashes.en.yml
  src/Resources/translations/flashes.fr.yml
  src/Resources/translations/messages.en.yml
  src/Resources/translations/messages.fr.yml
  src/Resources/views/payWithPaypal.html.twig
Labels: Enhancement

#179 Use sylius twig filter to get the proper province name
  src/Resources/views/payWithPaypal.html.twig
Labels: Enhancement

#174 Remove conflict in composer.json
  composer.json
Labels: Maintenance

#186 Doc: fix configuration key in sandbox-vs-live.md file
  docs/sandbox-vs-live.md
Labels: Bug, Maintenance

#197 Add official plugin badge
  README.md
Labels: Maintenance

#195 Build paypal with sylius 1.8 and 1.9
  .github/workflows/build.yml
  composer.json
  src/Controller/CancelPayPalPaymentAction.php
  src/Controller/EnableSellerAction.php
  src/Controller/PayPalOrderItemController.php
  src/Controller/ProcessPayPalOrderAction.php
  src/Controller/UpdatePayPalOrderAction.php
  src/Onboarding/Processor/BasicOnboardingProcessor.php
  tests/Application/.env
  tests/Application/Kernel.php
  tests/Application/config/bundles.php
  tests/Application/config/packages/_sylius.yaml
  tests/Application/config/packages/framework.yaml
  tests/Application/config/sylius/1.8/bundles.php
  tests/Application/config/sylius/1.8/packages/dev/jms_serializer.yaml
  tests/Application/config/sylius/1.8/packages/framework.yaml
  tests/Application/config/sylius/1.8/packages/jms_serializer.yaml
  tests/Application/config/sylius/1.8/packages/prod/jms_serializer.yaml
  tests/Application/config/sylius/1.8/routes/dev/twig.yaml
  tests/Application/config/sylius/1.9/bundles.php
  tests/Application/config/sylius/1.9/packages/dev/jms_serializer.yaml
  tests/Application/config/sylius/1.9/packages/jms_serializer.yaml
  tests/Application/config/sylius/1.9/packages/prod/jms_serializer.yaml
  tests/Application/public/index.php
  tests/Behat/Context/Admin/ManagingOrdersContext.php
Labels: Bug, Maintenance

#194 [Bug] Locale support improved
  spec/Processor/LocaleProcessorSpec.php
  src/Processor/LocaleProcessor.php
Labels: Bug
