Repository Sylius/PayPalPlugin, pull requests merged in 2021-09, with the labels that each got.

#209 [Build] Fix coding standards
  src/DependencyInjection/SyliusPayPalExtension.php
  src/Provider/OrderItemNonNeutralTaxesProvider.php
  src/Provider/OrderItemNonNeutralTaxesProviderInterface.php
  src/Provider/PayPalItemDataProvider.php
Labels: Bug, Maintenance

#210 Take care about `sylius_core.prepend_doctrine_migrations` parameters on 1.2
  src/DependencyInjection/SyliusPayPalExtension.php
Labels: Bug

#212 Propose a Github PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: DX, Enhancement

#213 Force decimal precision on create order
  spec/Api/CreateOrderApiSpec.php
  spec/Provider/PayPalItemDataProviderSpec.php
  src/Api/CreateOrderApi.php
  src/Provider/PayPalItemDataProvider.php
Labels: Bug

#203 Drop support for Sylius 1.8
  .github/workflows/build.yml
  composer.json
  tests/Application/Kernel.php
  tests/Application/config/routes/sylius_shop.yaml
  tests/Application/config/sylius/1.10/packages/security.yaml
  tests/Application/config/sylius/1.8/bundles.php
  tests/Application/config/sylius/1.8/packages/_sylius.yaml
  tests/Application/config/sylius/1.8/packages/dev/jms_serializer.yaml
  tests/Application/config/sylius/1.8/packages/framework.yaml
  tests/Application/config/sylius/1.8/packages/jms_serializer.yaml
  tests/Application/config/sylius/1.8/packages/prod/jms_serializer.yaml
  tests/Application/config/sylius/1.8/packages/security.yaml
  tests/Application/config/sylius/1.8/routes/dev/twig.yaml
  tests/Application/config/sylius/1.8/routes/sylius_admin_api.yaml
  tests/Application/config/sylius/1.9/packages/security.yaml
Labels: Maintenance
