Repository Sylius/PayPalPlugin, pull requests merged in 2022-01, with the labels that each got.

#227 Add support for sylius 1.11, drop support for sylius 1.9
  .github/workflows/build.yml
  composer.json
  src/DependencyInjection/SyliusPayPalExtension.php
  tests/Application/.env
  tests/Application/.env.test
  tests/Application/Kernel.php
  tests/Application/config/api_platform/config.yaml
  tests/Application/config/bundles.php
  tests/Application/config/packages/security.yaml
  tests/Application/config/sylius/1.10/bundles.php
  tests/Application/config/sylius/1.9/bundles.php
  tests/Application/config/sylius/1.9/packages/_sylius.yaml
  tests/Application/config/sylius/1.9/packages/dev/jms_serializer.yaml
  tests/Application/config/sylius/1.9/packages/jms_serializer.yaml
  tests/Application/config/sylius/1.9/packages/prod/jms_serializer.yaml
  tests/Application/config/sylius/1.9/packages/security.yaml
  tests/Application/config/sylius/1.9/routes/sylius_admin_api.yaml
Labels: Maintenance

#228 Allow to run Github Actions manually
  .github/workflows/build.yml
Labels: DX, Enhancement, Maintenance

#229 Fix build
  src/DependencyInjection/SyliusPayPalExtension.php
Labels: Bug

#230 Change supported branches to 1.3+
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: Maintenance
