Repository Sylius/PayPalPlugin, pull requests merged in 2022-10, with the labels that each got.

#263 [Maintenance] Add support for Symfony 6
  .github/workflows/build.yml
  composer.json
  phpstan.neon
  phpunit.xml.dist
  spec/Factory/PayPalPaymentMethodNewResourceFactorySpec.php
  spec/Provider/OrderProviderSpec.php
  src/Controller/CancelPayPalOrderAction.php
  src/Controller/CancelPayPalPaymentAction.php
  src/Controller/PayPalPaymentOnErrorAction.php
  src/Listener/PayPalPaymentMethodListener.php
  src/Provider/FlashBagProvider.php
  src/Resources/config/services.xml
  src/Resources/config/services/controller.xml
  src/Resources/config/shop_routing.yaml
  src/Resources/views/Buttons/cart.html.twig
  src/Resources/views/Buttons/payment.html.twig
  src/Resources/views/Buttons/productDetails.html.twig
  tests/Application/.env
  tests/Application/Kernel.php
  tests/Application/config/bootstrap.php
  tests/Application/config/bundles.php
  tests/Application/config/packages/security.yaml
  tests/Application/config/packages/security_checker.yaml
  tests/Application/config/packages/test/framework.yaml
  tests/Application/config/packages/test_cached/framework.yaml
  tests/Application/config/sylius/1.11/packages/dev/swiftmailer.yaml
  tests/Application/config/sylius/1.11/packages/staging/swiftmailer.yaml
  tests/Application/config/sylius/1.11/packages/swiftmailer.yaml
  tests/Application/config/sylius/1.11/packages/test/swiftmailer.yaml
  tests/Application/config/sylius/1.11/packages/test_cached/swiftmailer.yaml
  tests/Application/config/sylius/1.12/packages/mailer.yaml
  tests/Application/config/sylius/1.12/packages/test/mailer.yaml
  tests/Application/config/sylius/1.12/packages/test_cached/mailer.yaml
  tests/Application/public/index.php
  tests/Behat/Resources/services.xml
  tests/Behat/Resources/services/mailer.php
  tests/Behat/Resources/suites.yml
  tests/Behat/Resources/sylius-1.10/suites.yml
Labels: Maintenance

#266 [Maintenance] Route updated, force up-to-date sylius/sylius
  composer.json
  tests/Application/config/routes/sylius_shop.yaml
Labels: Bug

#267 [Symfony 6] Depend on the development version of Sylius
  .github/workflows/build.yml
  composer.json
Labels: Bug, Maintenance
