Repository Sylius/PayPalPlugin, pull requests merged in 2025-03, with the labels that each got.

#340 [Shop] Fix paypal checkout when another payment method was selected during checkout
  .github/workflows/build.yml
  UPGRADE.md
  src/Controller/CreatePayPalOrderFromCartAction.php
  src/Factory/PayPalPaymentMethodNewResourceFactory.php
  src/Resources/config/services/controller.xml
  tests/DataFixtures/ORM/resources/new_cart_with_cash_on_delivery_method.yaml
  tests/DataFixtures/ORM/resources/shop.yaml
  tests/Functional/CreatePayPalOrderFromCartActionTest.php
Labels: Bug

#341 [CI] Add upmerge from 1.6 to 1.7
  .github/workflows/upmerge_pr.yaml
Labels: Maintenance

#343 Revert BC break changes
  UPGRADE.md
  src/Controller/ProcessPayPalOrderAction.php
  src/Controller/UpdatePayPalOrderAction.php
  src/Resources/config/services/controller.xml
Labels: DX, Maintenance

#346 [Bug] Fix amount change on checkout
  UPGRADE.md
  spec/Payum/Action/CaptureActionSpec.php
  src/Controller/CompletePayPalOrderFromPaymentPageAction.php
  src/Controller/ProcessPayPalOrderAction.php
  src/Exception/PaymentAmountMismatchException.php
  src/Payum/Action/CaptureAction.php
  src/Resources/config/services.xml
  src/Resources/config/services/controller.xml
  src/Verifier/PaymentAmountVerifier.php
  src/Verifier/PaymentAmountVerifierInterface.php
  tests/Unit/PaymentAmountVerifierTest.php
Labels: Bug

#355 [Bug] Fix issue after paypal checkout
  spec/Processor/PayPalOrderCompleteProcessorSpec.php
  src/Processor/PayPalOrderCompleteProcessor.php
  src/Resources/config/services.xml
Labels: Bug

#360 Ensure PayPal shipping address is updated instead of overwritten
  UPGRADE.md
  spec/Payum/Action/CompleteOrderActionSpec.php
  src/Api/UpdateOrderAddressApi.php
  src/Api/UpdateOrderAddressApiInterface.php
  src/Controller/UpdatePayPalOrderAction.php
  src/Payum/Action/CompleteOrderAction.php
  src/Processor/PayPalAddressProcessor.php
  src/Processor/PayPalAddressProcessorInterface.php
  src/Resources/config/services.xml
  src/Resources/config/services/api.xml
  src/Resources/config/services/payum.xml
  tests/Unit/Api/UpdateOrderAddressApiTest.php
Labels: Bug
