Repository Sylius/PayPalPlugin, pull requests merged in 2025-01, with the labels that each got.

#331 Add new addToCart controller
  config/routes/shop.yaml
  config/services/controller.xml
  src/Controller/AddToCartAction.php
  src/Controller/PayPalButtonsController.php
  templates/pay_from_product_page.html.twig
  templates/shop/product/show/content/info/summary/paypal_checkout.html.twig
Labels: Bug

#333 [Maintenance] Move routes to sylius_shop_override_routing.yaml
  UPGRADE.md
  src/Resources/config/shop_routing.yaml
  src/Resources/config/sylius_shop_override_routing.yaml
Labels: Maintenance

#304 Add German translations for PayPal messages
  src/Resources/translations/flashes.de.yml
  src/Resources/translations/messages.de.yml
Labels: Enhancement

#334 [CI] Bump Sylius version to the stable one
  .github/workflows/build.yaml
Labels: Maintenance

#336 Remove unnecessary fos_rest configuration
  tests/Application/config/packages/sylius_paypal.yaml
Labels: Maintenance
